#!/usr/bin/env python3
"""Download and filter StarCoderData for pretraining.

Streams bigcode/starcoderdata filtered by programming language.

Usage:
    python download_code.py [--max-docs N] [--output-dir DIR]
"""

import argparse
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from clean import clean_document
from utils import write_jsonl

# Language sub-ratios within the code budget
LANGUAGE_CONFIG = {
    "go": 0.35,
    "python": 0.25,
    "javascript": 0.12,
    "typescript": 0.08,
    "shell": 0.10,
    "sql": 0.10,
}

# Auto-generated file markers
AUTO_GENERATED_MARKERS = [
    "generated by", "do not edit", "auto-generated", "automatically generated",
    "this file is generated", "code generated", "machine generated",
]


def is_auto_generated(text: str) -> bool:
    """Check if a file appears to be auto-generated."""
    header = text[:500].lower()
    return any(marker in header for marker in AUTO_GENERATED_MARKERS)


def download_language(lang: str, output_dir: Path, max_docs: int = 0):
    """Download one language from StarCoderData."""
    from datasets import load_dataset

    jsonl_path = output_dir / f"code_{lang}.jsonl"
    print(f"\n  Streaming {lang}...")

    ds = load_dataset("bigcode/starcoderdata", data_dir=lang, streaming=True, split="train")

    kept = 0
    seen = 0
    batch = []
    start = time.time()

    for doc in ds:
        seen += 1
        content = doc.get("content", "")

        # Quality filters
        if len(content) < 50 or len(content) > 100000:
            continue
        # Skip mostly non-ASCII (binary/minified)
        ascii_ratio = sum(1 for c in content[:1000] if ord(c) < 128) / min(len(content), 1000)
        if ascii_ratio < 0.5:
            continue
        if is_auto_generated(content):
            continue

        cleaned = clean_document(content, "code")
        if cleaned is None:
            continue

        batch.append({
            "text": cleaned,
            "source": "code",
            "language": lang,
        })

        if len(batch) >= 100:
            write_jsonl(jsonl_path, batch)
            batch = []

        kept += 1
        if kept % 10000 == 0:
            elapsed = time.time() - start
            print(f"    {lang}: {kept:,} kept / {seen:,} seen ({kept/elapsed:.0f}/s)")

        if max_docs and kept >= max_docs:
            break

    if batch:
        write_jsonl(jsonl_path, batch)

    elapsed = time.time() - start
    print(f"    {lang}: {kept:,} kept / {seen:,} seen in {elapsed:.0f}s")
    return kept


def main():
    parser = argparse.ArgumentParser(description="Download StarCoderData for pretraining")
    parser.add_argument("--output-dir", default="data/pretrain/code")
    parser.add_argument("--max-docs-per-lang", type=int, default=0, help="0 = use ratio-based budget")
    parser.add_argument("--total-budget", type=int, default=500000, help="Total docs across all languages")
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Downloading StarCoderData")
    print(f"  Languages: {', '.join(LANGUAGE_CONFIG.keys())}")
    print(f"  Total budget: {args.total_budget:,} docs")

    total_kept = 0
    for lang, ratio in LANGUAGE_CONFIG.items():
        max_docs = args.max_docs_per_lang or int(args.total_budget * ratio)
        kept = download_language(lang, output_dir, max_docs=max_docs)
        total_kept += kept

    print(f"\n--- Code Download Complete ---")
    print(f"  Total: {total_kept:,} documents")
    print(f"  Output: {output_dir}")


if __name__ == "__main__":
    main()
